version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: survivor-pool-client
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
