language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
notifications:
  slack:
    secure: wCaeEKFpOYSOmpnBrn3Fp3YHlcUtYTURsHjBTKbXZe/++igi1DxrBUt1ykEOGkjWNAwUml4K1g0kqD23LZ3mehcRY8S8K0whX+5OeJ22bNHoVHL9SN3WKGwTIE7+8LHhuYIKV3SxMAUDtRQ+/aGslOii6k3/uYlboTycxCWeuQJiVXK15GEOYE4DPvg1F9Igu5bE66Vry4W/pFUN3t+64bHLqbP4w6y8bOkbdHjtfa6f+ICLaKv6Vj4SD3iyOSCfgjRbVpyTY16cmVD+gP9BxVCfgjIdIsCKIgR0AHJVPk3iN7Fyk85gUcpJrJRk+Sw9HHrse4z/lfWQg7L56ZMawY38pJXDigcvI6P6a1QjesYk6kfAJo49qIn9/lQ9LgDtni+NcZ8jN147NzAlnxAEfQS+oXt7u+VsaaRtuf7R/YvIAHWXHop8fi3ou6ZA8PXqVnwKjqMTlEUKl/OzR0WNfOnhGy6B+HxhDHydX2+lOjmzx0XirrFC/0OSaayJTnThPUvyPb1Am0gHdhWJAFRj7yf/01SzWjpJnujZiOkPg66FyqvY7uMGsQSfIR2FgvUfSmMYeLyUWCTQ5nRmBsWn509EZzMWJqJguE6Si1VUG0vS96g+65SjuEFMKGD8n6GtDlzgJmIypQtLM2ujAN1O/Y6MQ5m+pg4EmFyJNAsEbwI=
